### ISSUE TITLE
Ideas widget is giving an Internal Server Error

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplit.github.io#2]

**Comment by CryZe** [comment]
I feel like we should just get rid of it. No one is looking at it anyway.

**Comment by wooferzfg** [comment]
People are still posting on there all the time, but I guess we're not really using that for prioritizing what features we add anymore. We should add a question to the FAQ on how to suggest ideas (probably just use Twitter?) if we do remove it.

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit.github.io/commit/abcd51c0669a48342fe3a9ff9195b27e78fbe8bc
